### ISSUE TITLE
[Bug Report] Render Mujoco environment and encounter an error

### ISSUE THREAD

**Issue by sxzhuang** [Farama-Foundation/Gymnasium#756]
### Describe the bug

I'm trying to render a Mujoco environment and encounter the following error when using the following code
```
import gymnasium as gym
env = gym.make("Walker2d-v4", render_mode="human")
observation, info = env.reset()

for _ in range(1000):
    action = env.action_space.sample()  # agent policy that uses the observation and info
    observation, reward, terminated, truncated, info = env.step(action)

    if terminated or truncated:
        observation, info = env.reset()

env.close()
```
The error shows the following message
```
Traceback (most recent call last):
  File "/workspace/rldd/test2.py", line 33, in <module>
    observation, info = env.reset()
  File "/usr/local/lib/python3.8/dist-packages/gymnasium/wrappers/time_limit.py", line 75, in reset
    return self.env.reset(**kwargs)
  File "/usr/local/lib/python3.8/dist-packages/gymnasium/wrappers/order_enforcing.py", line 61, in reset
    return self.env.reset(**kwargs)
  File "/usr/local/lib/python3.8/dist-packages/gymnasium/wrappers/env_checker.py", line 57, in reset
    return env_reset_passive_checker(self.env, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/gymnasium/utils/passive_env_checker.py", line 186, in env_reset_passive_checker
    result = env.reset(**kwargs)
  File "/usr/local/lib/python3.8/dist-packages/gymnasium/envs/mujoco/mujoco_env.py", line 155, in reset
    self.render()
  File "/usr/local/lib/python3.8/dist-packages/gymnasium/envs/mujoco/mujoco_env.py", line 409, in render
    return self.mujoco_renderer.render(
  File "/usr/local/lib/python3.8/dist-packages/gymnasium/envs/mujoco/mujoco_rendering.py", line 673, in render
    return viewer.render()
  File "/usr/local/lib/python3.8/dist-packages/gymnasium/envs/mujoco/mujoco_rendering.py", line 413, in render
    update()
  File "/usr/local/lib/python3.8/dist-packages/gymnasium/envs/mujoco/mujoco_rendering.py", line 353, in update
    self._create_overlay()
  File "/usr/local/lib/python3.8/dist-packages/gymnasium/envs/mujoco/mujoco_rendering.py", line 593, in _create_overlay
    bottomleft, "Solver iterations", str(self.data.solver_iter + 1)
AttributeError: 'mujoco._structs.MjData' object has no attribute 'solver_iter'
```

If I change the environment to 'LunarLander-v2', this code can run without issues, and I can see the render window.

### System info

mujoco==3.0.0
gymnasium==0.29.1

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Gymnasium/issues) in the repo

**Comment by Kallinteris-Andreas** [comment]
pip install `mujoco<3`

**Comment by sxzhuang** [comment]
> This will be fixed on the next release (`1.0`), `0.29` does not support `mujoco==3.0.0`
> 
> temporary fix for `0.29` and older versions `pip install mujoco<3`

It works, and thank you so much for your response!!

**Comment by goekce** [comment]
@Kallinteris-Andreas can we pin the version in `pyproject.toml`? Currently gymnasium[mujoco] installs Mujoco 3.

https://github.com/Farama-Foundation/Gymnasium/blob/de909da30a1fe40288275da331fa7ad8e219a2bc/pyproject.toml#L44

**Comment by Kallinteris-Andreas** [comment]
@goekce no need, this issue is fixed in main

**Comment by goekce** [comment]
@Kallinteris-Andreas are you sure? I don't see any pin in `pyproject.toml`.

**Comment by Kallinteris-Andreas** [comment]
it is not pinned

it works with `mujuco>=2.1.5` (which includes `mujuco>3`)

**Comment by goekce** [comment]
@Kallinteris-Andreas I believe there is a misunderstanding. You mentioned indeed:

> This will be fixed on the next release (`1.0`), `0.29` does not support `mujoco==3.0.0`

But now you seem to have pinned it with https://github.com/Farama-Foundation/Gymnasium/pull/913

**Comment by skr3178** [comment]
Fix for Humanoid simulations too. 
[https://www.youtube.com/watch?v=OqvXHi_QtT0&t=74s](https://www.youtube.com/watch?v=OqvXHi_QtT0&t=74s)
> This will be fixed on the next release (`1.0`), `0.29` does not support `mujoco==3.0.0`
> 
> temporary fix for `0.29` and older versions `pip install mujoco<3`
