### PR TITLE
Fixed render bug in RecordVideo wrapper

### PR DESCRIPTION
**Pull request by lfwa**
# Description

Fixed a bug where the `RecordVideo` wrapper was trying to retrieve the non-existing attribute `last_frame` from `VideoRecorder` causing recordings to fail. This pull request reintroduces the `last_frame` attribute resolving the issue.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] I have run the [`pre-commit` checks](https://pre-commit.com/) with `pre-commit run --all-files` (see `CONTRIBUTING.md` instructions to set it up)
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by pseudo-rnd-thoughts — CHANGES_REQUESTED** [review]
Thanks for the PR, could you fix the pre-commit issue (https://github.com/Farama-Foundation/Gymnasium/blob/main/CONTRIBUTING.md)

Could you provide example code for this failing

**Comment by lfwa** [comment]
The pre-commit issue looks to be related to changes introduced in https://github.com/Farama-Foundation/Gymnasium/pull/117. pyright complains about `env_checker.py:311:32 - error: "make" is not a known member of "None"`.

Example code throwing this error would be:
```python
import gymnasium as gym

env = gym.make("CartPole-v1", render_mode="rgb_array")
env = gym.wrappers.RecordVideo(env, video_folder="./videos")
obs = env.reset()
env.render()

observation, info = env.reset(seed=42)
for _ in range(1000):
    action = (
        env.action_space.sample()
    )  # this is where you would insert your policy
    observation, reward, terminated, truncated, info = env.step(action)

    if terminated or truncated:
        observation, info = env.reset()
    env.close()
```

Resulting in `AttributeError: 'VideoRecorder' object has no attribute 'last_frame'` before the change.

**Comment by pseudo-rnd-thoughts** [comment]
I have just fixed the pre-commit issue in main, if you update to it, this should remove the issues

**Comment by lfwa** [comment]
Done and in my use case it was just to render the initial environment for inspection before proceeding with the recording.

Regarding the fix, it would also be possible to remove the logic in `record_video.py` that accesses `last_frame` if you do not want to reintroduce it inside `video_recorder.py`.

**Comment by lfwa** [comment]
@younik, thanks!

I removed the `last_frame` access in `RecordVideo` and undid the other changes as per your suggestion. I'll consider submitting a refactoring in the future but perhaps we can keep it simple for now :)

**Review by younik — APPROVED** [review]
Great, LGTM

**Review by pseudo-rnd-thoughts — APPROVED** [review]
